
  # Publish all joint states ___________________________________
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ______________________________________
  right_front_shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_shoulder_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  right_front_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_knee_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  right_back_shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_shoulder_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  right_back_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_knee_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  left_front_shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_shoulder_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  left_front_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_knee_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  left_back_shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_shoulder_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  left_back_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_knee_joint
    pid: {p: 100.0, i: 0.001, d: 0.001}
  
